version: "3.8"

services:
  db:
    image: mysql:8.0.31
    container_name: db
    profiles:
      - db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:6.1.1-fpm-alpine
    container_name: wordpress
    profiles:
      - wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.23-alpine
    container_name: webserver
    profiles:
      - webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot:v1.32.0
    container_name: certbot
    profiles:
      - certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    #command: certonly --webroot --webroot-path=/var/www/html --email bensuperpc@bensuperpc.fr --agree-tos --no-eff-email --staging -d www.test.bensuperpc.fr -d test.bensuperpc.fr
    command: certonly --webroot --webroot-path=/var/www/html --email bensuperpc@bensuperpc.fr --agree-tos --no-eff-email --force-renewal -d www.test.bensuperpc.fr -d test.bensuperpc.fr

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    profiles:
      - pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@admin.net}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin}"
    depends_on:
      - db
    ports:
      - 5050:5050
    networks:
      - app-network
volumes:
  certbot-etc: {}
  wordpress: {}
  dbdata: {}

networks:
  app-network:
    driver: bridge