version: "3.8"

services:
  db:
    image: mysql:8.0.31
    container_name: db
    profiles:
      - db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:6.1.1-php8.1-fpm
    container_name: wordpress
    profiles:
      - wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.23
    container_name: webserver
    profiles:
      - webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt:ro
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot:v1.32.0
    container_name: certbot
    profiles:
      - certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    #command: certonly --webroot --webroot-path=/var/www/html --email bensuperpc@bensuperpc.fr --agree-tos --rsa-key-size 4096 --no-eff-email --verbose --noninteractive --staging -d www.bensuperpc.org -d bensuperpc.org
    #command: certonly --webroot --webroot-path=/var/www/html --email bensuperpc@bensuperpc.fr --agree-tos --rsa-key-size 4096 --no-eff-email --force-renewal -d www.bensuperpc.org -d bensuperpc.org
    command: certonly --webroot --webroot-path=/var/www/html --email bensuperpc@bensuperpc.fr --agree-tos --rsa-key-size 4096 --no-eff-email --verbose --noninteractive --keep-until-expiring -d www.bensuperpc.org -d bensuperpc.org
  phpmyadmin:
    image: phpmyadmin:5.2.0-fpm
    container_name: phpmyadmin
    profiles:
      - phpmyadmin
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - app-network
volumes:
  certbot-etc: {}
  wordpress: {}
  dbdata: {}

networks:
  app-network:
    driver: bridge